### ISSUE TITLE
Testing Environment

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint#11]
Add travis and integration tests to the solution and document this in more detail.

**Comment by eckelj** [comment]
The goal is to integration API tests containing all major transaction types:
* CREATE
*  TRANSFER
* Threshold signatures (multisig)

Start the just build binary (native or via docker) send transaction via API, verify results via API. 
Are the acceptance test executed during pull requests: https://github.com/bigchaindb/bigchaindb/tree/master/acceptance?

**Comment by LaurentDeMontBlanc** [comment]
The bigchaindb acceptance test are executed during a pull request for python 3.6 or higher (as can be seen here: https://app.travis-ci.com/github/bigchaindb/bigchaindb/jobs/551011600)

**Comment by LaurentDeMontBlanc** [comment]
@eckelj I think for the validator tests (election, voting, ..) it would be possible to update the existing bigchaindb-node-ansible playbook and execute the updated playbook for creating, updating and electing new nodes and tearing them down afterwards. I have created a short draft for this on the canban board
