### ISSUE TITLE
add TarantoolDBConnection class

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint#113]
The `TarantoolDB` class exists in multiple files, it should be renamed and moved.

ToDos:
 - remove all copies of the `TarantoolDB` class except for `planetmint/backend/tarantool/connection.py::TarantoolDB`
 - rename to `TarantoolDBConnection` to be coherent with `LocalMongoDBConnection`
 - `TarantoolDBConnection` inherits from `planetmint/backend/connection.py::Connection`
 - implement `Connection` in `TarantoolDBConnection`

**Comment by ArpitShukla007** [comment]
As already discussed, for implementing the `Connection` class in the `TarantoolDB` class, there are basically 2 functions:

1. `_connect` function which can be implemented by renaming the current `reconnect` function 
2. `run` function to run the different queries.

**Comment by andreitricolici** [comment]
How to implement this mechanism for Tarantool.
1) Add `query()` method to TarantoolDBConnection.
2) Modify `space()` method from TarantoolDBConnection, that it will return Lazy object.
3) Add `run()` method to TarantoolDBConnection, so that we can run our queries.

This is a test script that shows how it should work with Tarantool. Try it !

```
import tarantool


class Lazy:

    def __init__(self):
        """Instantiate a new Lazy object."""
        self.stack = []

    def __getattr__(self, name):
        self.stack.append(name)
        return self

    def __call__(self, *args, **kwargs):
        self.stack.append((args, kwargs))
        return self

    def __getitem__(self, key):
        self.stack.append('__getitem__')
        self.stack.append(([key], {}))
        return self

    def run(self, instance):
        """Run the recorded chain of methods on `instance`.

        Args:
            instance: an object.
        """

        last = instance

        for item in self.stack:
            if isinstance(item, str):
                print(item)
                last = getattr(last, item)
            else:
                last = last(*item[0], **item[1])

        self.stack = []
        return last


class TarantoolDB:
    def __init__(self):
        self._connection = self.connection()

    def connection(self):
        return tarantool.connect("localhost", 3303)

    def query(self):
        return Lazy()

    def space(self, space_name):
        return self.query().space(space_name)

    def run(self, query):
        return query.run(self._connection).data


conn = TarantoolDB()
res = conn.run(
    conn.space("assets").insert(({"test": "data"}, "abc123", "abc111"))
)
res = conn.run(
    conn.space("assets").select([])
)
print(res)
```

**Comment by LaurentDeMontBlanc** [comment]
After some investigation I found out that the spaces were actually never created. The `run_command_with_output` tried to connect to `tarantool` with `localhost:3303`. This needs to be replaced with values from the `Config()`.
