### ISSUE TITLE
add localmongodb tests back in

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint#116]
As soon as Connection is implemented in a more generic way we need to add the localmongodb test cases back to the test suite.

ToDos:
 - make db connection configurable for test execution
 - add tarantool and localmongodb configuration to test matrix
 - add localmongodb tests back to the test suite

**Comment by LaurentDeMontBlanc** [comment]
@andreitricolici the following fixtures are concerned with the db connection `_bdb`, `_setup_database`, `_configure_planetmint` in `tests/conftest.py`. Those need to be adjusted to select the correct db connection type per test case if a test is indeed db specific.

For example on the `planetmint-tarantool` branch the `_configure_planetmint` fixture has `backend = "tarantool_db"` hardcoded. This should be read from the `Config`. A possible solution would be to add a marker that updates the `Config` accordingly to the test case (e.g.: a `pytest.mark.localmongodb` and `pytest.mark.tarantool`). Then in turn the fixtures calling for the `Config` object would automatically create the correct db connection for the specific test case.

Additionally the docker-compose.yml could startup both db services as long as no ports are conflicting. Then all tests should be executable in a single test run.

**Comment by LaurentDeMontBlanc** [comment]
@andreitricolici when this issue is done https://github.com/planetmint/planetmint/issues/125 we need to add a step so that the database connection is freshly instantiated after the config has change because `Connection()` will always return the first instance created otherwise
