### ISSUE TITLE
Fix planetmint test cases

### ISSUE THREAD

**Issue by andreitricolici** [planetmint/planetmint#128]
We have to fix test cases. You can take any folder you want. but write in comments what folder you are working on.
Or if it is a file in a root folder of tests/. You can just write the path of file.

**Comment by andreitricolici** [comment]
I am working on tests/backend/tarantool/test_queries.py

**Comment by roninx991** [comment]
I believe many of the test cases can be fixed if the db gets re-initialized. I think it's not happening right now

**Comment by roninx991** [comment]
I'll be working on tendermint/test_core.py. Some of those issues are easy to fix

**Comment by andreitricolici** [comment]
tests/backend/tarantool/test_queries.py FIXED.
+ I fixed flush_db_tarantool now it removes data from blocks and blocks_tx spaces.

**Comment by andreitricolici** [comment]
i will be work now on tests/test_core.py

**Comment by andreitricolici** [comment]
I will work on tests/tendermint/test_core.py
