### ISSUE TITLE
Problem with fetching assets

### ISSUE THREAD

**Issue by ArpitShukla007** [planetmint/planetmint#142]
# Problem

Failing test: `tests/web/test_block_tendermint.py::test_get_block_endpoint - KeyError: 'id'`

- Currently, when `get_assets` function of Tarantool query is called by passing asset id list as argument, it returns all the fetched assets in a sorted order.
-  But, the issue occurs in the above shown test-case where a `CREATE` transaction creates a new asset (without `asset id`) 
- Hence, the keyerror occurs as the sort by id function in `planetmint/backend/tarantool/query.py` as it could not find any id.

# Possible issues

- The function call to `get_assets` instead of `get_asset` while fetching a single asset
- The issue in logic of storing and retrieval of asset id in Tarantool in the case of a single asset

# Possible solutions

- Check the length of asset id list passed in `get_assets` and if the length is 1 then skip sorting and return that single asset directly. 
- Store the asset id along the asset in Tarantool
- Append the asset id along with asset in `_returned_data` externally in `get_assets` function

**Comment by andreitricolici** [comment]
We could get "hash sum is different" error, if we will add 'id' field to asset object, if he didn't have it la crearea tranzactiei

**Comment by ArpitShukla007** [comment]
### Further possible issue

- There is no table/collection level schema defined in the MongoDB implementation. Only the indices are defined such as:
```
 'assets': [
        ('id', dict(name='asset_id', unique=True)),
        ([('$**', TEXT)], dict(name='text')),
    ],
```
- In Tarantool, the schema is defined as follows:
```
"assets":
        "assets:format({{name='data' , type='any'}, {name='tx_id', type='string'}, {name='asset_id', type='string'}})",
```

- Now, when I checked the asset being stored in the asset collection using `store_asset` function in Tarantool, I found that asset is being stored in following way: 
```
Asset stored:
({'data': {'cycle': 'hero'}}, '885acc038140b4d4d7399cd02663dcd03bb9e0f52a2d6628081d0e77931eb8ba', '885acc038140b4d4d7399cd02663dcd03bb9e0f52a2d6628081d0e77931eb8ba')

```

### Possible solution

- Check on assets after inserting the asset object according to the schema defined in Tarantool

**Comment by ArpitShukla007** [comment]
Adding some more findings here:

- The `get_asset` function in `planetmint/backend/tarantool/query.py` returns `_data[0][0]` which is only thew 1st index of the asset row (i.e., the `data` field). 
- It is seen that with store_bulk_transactions we use `insert_many` where PyMongo automatically adds an `_id` field to the tx, therefore we need the deepcopy. We need to check the same for Tarantool as well.

**Comment by andreitricolici** [comment]
**Functions get_asset and get_assets from backend/query.py are used in following files.**
1) lib.py::get_transaction
2) lib.py::get_assets
3) transactions.py:Transaction::from_db
