### ISSUE TITLE
remove tarantool logic Transaciton model 

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint#161]
## Description
The `from_db()` function in the planetmint-tarantool has a step where it expects a tuple whilst it should be a dict. 

## Current State (planetmint-tarantool):
```python
assets = list(planet.get_assets(tx_ids))
for asset in assets:
   if asset is not None:
     # This is tarantool specific behaviour needs to be addressed
     tx = tx_map[asset[1]]
     tx['asset'] = asset[0]
```

## Proposed State (previous implementation on main)
```python
assets = list(planet.get_assets(tx_ids))
for asset in assets:
  if asset is not None:
    tx = tx_map[asset["id"]]
    del asset["id"]
     tx["asset"] = asset
```

## ToDos
 - change `planetmint/backend/tarantool/queries.py::get_assets()` so it returns the asset in the same form as mongodb
 - check where the `get_assets()` query was used and if other core components have been adjusted to that behaviour
 - repair test cases that probably have been changed as well

**Comment by andreitricolici** [comment]
## Problem
Researching this problem, i saw that, main problem is in **planetmint/lib.py::store_bulk_transctions**.
This function is entry point for processing transactions. 
Take a look at this diagram before you will continue: **https://lucid.app/lucidchart/7354bfae-e603-4774-a2e5-1c1a90ec103c/edit?page=0_0&invitationId=inv_09fe98dd-16c2-4b7b-8b74-02247b285a3f#**
