### ISSUE TITLE
repair integration test suite on planetmint-tarantool

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint#163]
## Description
The integration tests are failing at the moment on `planetmint-tarantool`. This is probably because the of some configuration issues during startup. This needs some investigation why the planetmint instance is not able to start.

## ToDos:
 - compare integration test suite to acceptance test suite
 - fix configuration issue

**Comment by LaurentDeMontBlanc** [comment]
My current findings are the following:
 - `Dockerfile-all-in-one` was still using mongodb
 - `integration/scripts/all-in-one.bash` was also still configured for mongodb
 - currently the tendermint process is failing due to db connection issues => need to check where this is defined
