### ISSUE TITLE
"Pull access denied" attempting to download Planetmint Docker image

### ISSUE THREAD

**Issue by random-pixels** [planetmint/planetmint#286]
# Configuration
I'm using Linux Mint 21 (Ubuntu-based Linux distribution). I have Docker Desktop installed and running (version 4.11 currently).
Trying to follow the instructions to obtain the Docker container provided in this documentation:
https://docs.planetmint.io/en/latest/node-setup/index.html#run-planetmint-with-all-in-one-docker
I get stuck on step 1.

# Issue/Errors

> ~$ **docker pull planetmint/planetmint:all-in-one**
> Error response from daemon: pull access denied for planetmint/planetmint, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

If some sort of credentials or account creation is required, perhaps this could be mentioned in the documentation? If not, perhaps the command (or repository) could be updated so that it works?

I then tried to clone the GitHub repo as per the documentation on the same page, and it also doesn't work (without a whole lot of additional configuration on the part of the user, plus a GitHub account.)

> ~$ **git clone git@github.com:planetmint/planetmint.git**
> Cloning into 'planetmint'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights and the repository exists.

There is a working (and more secure) version of this command on the GitHub repo README file, so I'm hoping the documentation page can be updated with this working command:

> ~$ **git clone https://github.com/planetmint/planetmint.git**
> Cloning into 'planetmint'...
> remote: Enumerating objects: 8316, done.
> remote: Counting objects: 100% (2100/2100), done.
> remote: Compressing objects: 100% (727/727), done.
> remote: Total 8316 (delta 1415), reused 1963 (delta 1320), pack-reused 6216
> Receiving objects: 100% (8316/8316), 4.74 MiB | 695.00 KiB/s, done.
> Resolving deltas: 100% (5758/5758), done.

# checkboxes:

- [ ] documentation at: [Docker documentation](https://docs.planetmint.io/en/latest/node-setup/index.html#run-planetmint-with-all-in-one-docker)

**Comment by eckelj** [comment]
@random-pixels you're right. thank you for mentioning that. we didn't publish any docker images for planetmint so far. we alaways buld them locally via e.g. `docker-compose build planetmint`

thank you for reminding us to publish these with each release.
