### ISSUE TITLE
Add Zenroom support to planetmint

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint#3]

**Comment by albertolerda** [comment]
Here https://github.com/albertolerda/bigchaindb/blob/zenroom-integration/testtom/mytest.py you can find a proposal for the interface between zenroom and bigchaindb.
While here https://github.com/albertolerda/cryptoconditions/blob/zenroom-integration/cryptoconditions/types/zenroom.py there is a possible implementation of the cryptoconditions for zenroom.
