### ISSUE TITLE
Restructue Documentation

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint#31]

**Comment by emotemot** [comment]
How should we name our documentation hub repo? Open for ideas.

- planetmint-doc-hub
- planetmint-documentation

**Comment by eckelj** [comment]
I propose the following planetmint docs restructure. I think that we can recycle a lot and get it more streamlined so that a there is a clear overview on where to find what (I had a look at https://docs.tendermint.com/)

* introduction  
   * quick start
   * Installation
   * what is planetmint (about)
* tutorials
   * Basic Usage (including the tutorials or somewhere else on the page)
   * connection to a node
* Building Networks & Federations
   * set up a node
   * set up a network
   * set up a federation
* Understanding Planetmint
* Spec
   * Bindings (Drivers - how to connect)
   * Interfaces
* Tooling
   * Overview
   * Debugging
   * Docker Compose
   * Terraform & Ansible
   * Operations


Don't:
* Properties of Planetmint: we should remove the properties and move them to the product description or the website

**Comment by eckelj** [comment]
This is the current structure:

[Introdcution]
[Using Planetmint]
[Node Setup]
[Networks & Federations]
[Connecting to Planetmint]
[Tools]
[Contributing to Planetmint]
[Terminology]
[Troubleshooting]

this is to be improved in the future.
