### ISSUE TITLE
fix subcondition instantiation

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint#314]
## Description
We've encountered an issue while storing an transaction with a weighted threshhold condition. The `Output.outputs_dict()` method either calls `output_with_public_key()` or `output_with_subcondition()` to instantiate an `Output` for storing it to the database. With virtually unlimited combinations of conditions and subconditions this should be handled recursively.

## ToDos
- rename `Output.outputs_dict()` to something that resembles it's functionality more
- make `Condition` / `SubCondition` instantiation recursive

## Current State
`Output.outputs_dict()` calls one of 2 functions.
```python
@staticmethod
def outputs_dict(output: dict, transaction_id: str = "") -> Output:
    out_dict: Output
    if output["condition"]["details"].get("subconditions") is None:
        out_dict = output_with_public_key(output, transaction_id)
    else:
        out_dict = output_with_sub_conditions(output, transaction_id)
    return out_dict
```
Those functions do basically the same thing except for their call to the `ConditionDetails()` constructor.
```python
def output_with_public_key(output, transaction_id) -> Output:
    return Output(
        transaction_id=transaction_id,
        public_keys=output["public_keys"],
        amount=output["amount"],
        condition=Condition(
            uri=output["condition"]["uri"],
            details=ConditionDetails(
                type=output["condition"]["details"]["type"],
                public_key=output["condition"]["details"]["public_key"],
            ),
        ),
    )


def output_with_sub_conditions(output, transaction_id) -> Output:
    return Output(
        transaction_id=transaction_id,
        public_keys=output["public_keys"],
        amount=output["amount"],
        condition=Condition(
            uri=output["condition"]["uri"],
            details=ConditionDetails(
                type=output["condition"]["details"]["type"],
                threshold=output["condition"]["details"]["threshold"],
                sub_conditions=[
                    SubCondition(
                        type=sub_condition["type"],
                        public_key=sub_condition["public_key"],
                    )
                    for sub_condition in output["condition"]["details"]["subconditions"]
                ],
            ),
        ),
    )
```

## Proposed State
The `ConditionDetails` and `SubCondition` should be instantiated recursively. The can be reduced to one `dataclass` like so:
```python
@dataclass
class ConditionDetails:
    type: str
    public_key: str
    threshold: int
    sub_conditions: list[ConditionDetails]
```
In this case the `type` of `ConditionDetails` can be simply taken to identify if further instantiation of children is needed.

**Comment by eckelj** [comment]
@LaurentMontBlanc I like the idea and the approach in general, but I suggest using an iterative solution instead of a recursive one.

Stack attacks can be avoided, and we have a more stable and resilient solution.
