### ISSUE TITLE
Change the documentation in such a way that Tarantool is referenced int he documentation

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint#34]
Pleaes iterate over the Docs/files and investigate where to replace MongoDB and mention Tarantool.

**Comment by liviu-lesan** [comment]
https://github.com/liviu-lesan/planetmint/commit/9f42bec2abaa65a59781b208758a2a485edd59e2

I left mongoldb reference just in one place where it's described how to use it with environment variables which is not a bad idea but has to be implemented.

**Comment by eckelj** [comment]
@LaurentMontBlanc please make a difference with tarantool at the following sections:

https://docs.planetmint.io/en/latest/introduction/index.html#install-planetmint
https://docs.planetmint.io/en/latest/node-setup/index.html#

and others if you think it makes sense to mention it there.
