### ISSUE TITLE
question: is there a way to know about the commit date of a transaction ?

### ISSUE THREAD

**Issue by getlarge** [planetmint/planetmint#402]
I was not able to find that information from `docs.planetmint.io`, maybe there is an OpenAPI specs that i could have a look at ?
This is not really an issue, unless there is no way to retrieve it.

**Comment by LaurentMontBlanc** [comment]
@getlarge it is possible to retrieve the commit date of a block. for txs itself i need to take another look or we need to specifically add a timestamp field
