### ISSUE TITLE
Compose Transactions

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint#51]
## preconditions
* before assets can be composed, they have to be owned by one entity
* COMPOSE transaction takes multiple assets as an input (all belonging to the same owner)
* Burns the input assets Z and create the new asset with a certain amount Y
* all transaction should be part of one block

**Comment by LaurentDeMontBlanc** [comment]
has been defined on PRP-5 and PRP-9 mentioning this on #69 and #70
