### ISSUE TITLE
Publish planemtint performance measurements

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint#68]
The performance of tendermint 0.34.15 is to be compared to the version of bigchaindb (oldest version /previous PRP6) and against the version 0.31.5 of the latest bigchaindb/main branch. 
the differences are to be published as a PR to PRP6 with a changelog as defined at https://keepachangelog.com/en/1.0.0/.
The PR should mention what got changed (file structure) and what got added as an overview at the top of the page.

**Comment by LaurentDeMontBlanc** [comment]
@eckelj are you doing this now for the EBSI testing or was this done in the past except for the changelog?
