### ISSUE TITLE
Add compose transaction class

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint#69]
- Add `Compose` class to `planetmint/transactions/types/assets/compose.py`
 - Adjust `Transaction` class in `planetmint/transactions/transaction.py` to support `COMPOSE` operation
 - Adjust `Transaction` class in `planetmint/models.py` to support `COMPOSE` operation
 - Add validation schema to `planetmint/transactions/common/schema/transaction_compose_v2.1.yaml` acoording to https://github.com/planetmint/PRPs/pull/6/files
 - Add unit tests to `tests/assets`. Initial tests should reflect use cases in https://github.com/planetmint/PRPs/pull/6/files

**Comment by LaurentDeMontBlanc** [comment]
Change to `v3.0`

**Comment by LaurentDeMontBlanc** [comment]
@ArpitShukla007 i created a first version of the `COMPOSE` schema. I wanted to give a few explanations for my decisions:
Starting with the simple stuff. The `assets` reference the transactions that are being used  to create the new asset and define the new asset.
```
assets: [
  {id: <ID of a transaction that is being partly or completely consumed>},
  {data: <any valid associative array>}
]
```
Moving on to the `inputs`. The inputs must be one of two kinds: consumed inputs and the newly created input.
```
inputs: [
  {
    "fulfills": {
        "transaction_id": transaction_id,
        "output_index": output_index
    },
    "owners_before": [public_key_1, public_key_2, etc.],
    "fulfillment": fulfillment
  },
  {
    "fulfills": ctnull,
    "owners_before": [public_key_1, public_key_2, etc.],
    "fulfillment": fulfillment
  },
]
```
Next up the `metadata`. The metadata has a required property called `consumption`, which is an array of references to inputs and the amount that is being consumed of said input.
```
metadata: {
  consumption: [
    {input_index: <index of the input in inputs>, amount: <amount that is being consumed>}
  ]
}
```
And finally the `outputs` must have a minimum length of one if the consumed input is consumed completely and two if some of the consumed inputs remain and will be locked with a condition. The amounts of the output elements must be smaller than input amounts. The amount in consumption and output must equal the input amount.

**Comment by ArpitShukla007** [comment]
> @ArpitShukla007 i created a [first version](https://github.com/LaurentDeMontBlanc/planetmint/blob/add-compose-transaction-class/planetmint/transactions/common/schema/v3.0/transaction_compose.yaml) of the `COMPOSE` schema. I wanted to give a few explanations for my decisions: Starting with the simple stuff. The `assets` reference the transactions that are being used to create the new asset and define the new asset.
> 
> ```
> assets: [
>   {id: <ID of a transaction that is being partly or completely consumed>},
>   {data: <any valid associative array>}
> ]
> ```
> 
> Moving on to the `inputs`. The inputs must be one of two kinds: consumed inputs and the newly created input.
> 
> ```
> inputs: [
>   {
>     "fulfills": {
>         "transaction_id": transaction_id,
>         "output_index": output_index
>     },
>     "owners_before": [public_key_1, public_key_2, etc.],
>     "fulfillment": fulfillment
>   },
>   {
>     "fulfills": ctnull,
>     "owners_before": [public_key_1, public_key_2, etc.],
>     "fulfillment": fulfillment
>   },
> ]
> ```
> 
> Next up the `metadata`. The metadata has a required property called `consumption`, which is an array of references to inputs and the amount that is being consumed of said input.
> 
> ```
> metadata: {
>   consumption: [
>     {input_index: <index of the input in inputs>, amount: <amount that is being consumed>}
>   ]
> }
> ```
> 
> And finally the `outputs` must have a minimum length of one if the consumed input is consumed completely and two if some of the consumed inputs remain and will be locked with a condition. The amounts of the output elements must be smaller than input amounts. The amount in consumption and output must equal the input amount.

@LaurentDeMontBlanc The draft LGTM! I just have a comment regarding the inputs. I think we need to keep inputs as required for compose transaction. Let's dive deeper and finalise it. Thanks.

**Comment by LaurentDeMontBlanc** [comment]
@ArpitShukla007 the inputs are already required, the models always validate against the `transaction.yaml` first and then against the specific type (e.g.: `transaction_compose.yaml`).

**Comment by LaurentMontBlanc** [comment]
@eckelj the `COMPOSE` transfer class has been added to `planetmint/transactions`. We still need to add it to `planetmint` and the `planetmint-python-driver`. Full implementation is done after the following tasks are completed:
 - add transaction validation `validate_compose_transaction` to the `planetmint/planetmint/lib.py::Planetmint` class
 - add `prepare_compose_transaction` to `planetmint-python-driver/planetmint_driver/offchain.py`
 - add `test_prepare_compose_transaction` to `planetmint-python-driver/tests/test_offchain.py`

### Transaction validation on planetmint service
 - validate that a new asset has been created
 - only one output is allowed for now
