### ISSUE TITLE
Support Tarantool as a storage solution

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint#7]
- architectural definition
-  [https://www.tarantool.io/en/download/os-installation/ubuntu/](https://www.tarantool.io/en/download/os-installation/ubuntu/)
-  investigation on how to migrate the current DB schema to a working tarantool schema, will we just replicate the current schema?
- We should start simple 
- do performance tests and improve the utilization of tarantool thereafter

**Comment by jaromil** [comment]
Some useful resources to get started:
- https://www.tarantool.io/en/doc/latest/getting_started/getting_started_cartridge/
- https://github.com/tarantool/crud

The yak is already shaved here, for deployement:
- https://hub.docker.com/r/dyne/tarantool/tags

in place of `centos7` base image for cartridges just use `dyne/tarantool:centos8`
