### ISSUE TITLE
Add decompose transaction class

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint#70]
- Add `Decompose` class to `planetmint/transactions/types/assets/decompose.py`
 - Adjust `Transaction` class in `planetmint/transactions/transaction.py` to support `DECOMPOSE` operation
 - Adjust `Transaction` class in `planetmint/models.py` to support `DECOMPOSE` operation
 - Add validation schema to `planetmint/transactions/common/schema/transaction_decompose_v2.1.yaml` acoording to https://github.com/planetmint/PRPs/pull/6/files
 - Add unit tests to `tests/assets`. Initial tests should reflect use cases in https://github.com/planetmint/PRPs/pull/6/files

**Comment by LaurentDeMontBlanc** [comment]
@ArpitShukla007 I noticed that the current schema does not allow for more than one asset per tx. So we will need a breaking change to `3.0` where the `asset` object will be replaced with an `assets` array. This drags some other changes along. Will follow up

**Comment by ArpitShukla007** [comment]
@LaurentDeMontBlanc I have finished [initial draft](https://github.com/ArpitShukla007/planetmint/blob/main/planetmint/transactions/common/schema/v3.0/transaction_decompose.yaml) of the `DECOMPOSE` schema. Here is the explanation to the logic implemented:

The `assets` refer to the array of assets containing the asset referring to the compose transaction as well as the other newly created assets by decomposition of the composed asset. The number of assets in `DECOMPOSE` transaction will always be at least 3 (i.e., `num_assets >= 3`). 

```
assets: [ 
    {id: <ID of a compose transaction that is being decomposed>},
    {data: <any valid associative array of the newly created assets>},
    {data: <any valid associative array of the newly created assets>},
    ...
]
```

Regarding the inputs, a `DECOMPOSE` transaction will be able to decompose exactly one composed asset (i.e., `num_inputs = 1`)

```
inputs: [
  {
    "fulfills": {
        "transaction_id": transaction_id,
        "output_index": output_index
    },
    "owners_before": [public_key_1, public_key_2, etc.],
    "fulfillment": fulfillment
  }
]
```

Finally regarding the outputs, each output in the outputs of DECOMPOSE transaction indicates the crypto-conditions to spend/transfer that output and the number of shares of the newly created assets tied to that output. The amount of newly created assets must be less than or equal to the consumption amount stored in the `metadata` of the `COMPOSE` transaction.

```
outputs: [ 
    {
        "condition": condition,
        "public_keys": [public_key_1, public_key_2, etc.],
        "amount": amount
    },
    {
        "condition": condition,
        "public_keys": [public_key_1, public_key_2, etc.],
        "amount": amount
    },
    {
        "condition": condition,
        "public_keys": [public_key_1, public_key_2, etc.],
        "amount": amount
    },
    ...
]

```

It is important to know that previous composed asset will be burn and the number of outputs will be at least 3 (i.e., `num_outputs >= 3`).

**Comment by LaurentMontBlanc** [comment]
@eckelj we have defined that a decompose transaction should create multiple outputs from breaking up a single input asset into multiple outputs. These outputs shall be locked until unlocked with either a `CREATE` or `TRANSFER` transaction. This is to create a unique tx id that serves as an asset id.

**Comment by LaurentMontBlanc** [comment]
@eckelj I would be in favor of `CREATE` transactions that fulfill the `DECOMPOSE` outputs. This way we would only need to check on the planetmint service if a `CREATE` input stems from a `DECOMPOSE` tx.

## ToDos:
 - implement `transactions/decompose.py::Decompose` class (`generate`, `validate_decompose` methods)
 - add `transaction_decompose.yaml` schema
 - add `validate_decompose_inputs` to `planetmint/lib.py`
 - adjust `CREATE` input validation
